### ISSUE TITLE
Cannot resolve supporting libraries.

### ISSUE THREAD

**Issue by hossenlopp** [DBCG/cqf-ruler#222]
The current revision of published Docker `contentgroup/cqf-ruler:develop` is unable to run connectathon measures. There seems to be an issue with referencing supporting Libraries.

For example running $evaluate-measure on EXM_125 errors out with the following error:
```
Failed to call access method: java.lang.IllegalArgumentException: Could not resolve library id http://fhir.org/guides/dbcg/connectathon/Library/library-FHIRHelpers|4.0.1"
```

**Comment by JPercival** [comment]
Hi @hossenlopp . This was caused by 3 issues:

1. A change in the way the connectathon measures were built which incorporated some new IG Publisher functionality (specifically, to build Libraries using the Publisher's new CQLSubsystem)
2. Missing corresponding functionality in the cqf-ruler for resolution.
3. The automated cqf-ruler testing silently being broken.

The cqf-ruler develop container has been fixed and updated. The cqf-tooling has also been updated. If you update the ruler container and then get latest from the connectathon repo, run _updateRefresh, and then _refresh, you should get passing Measures.

Fixing the automated tests is underway.

**Comment by hossenlopp** [comment]
Thanks @JPercival! The `_refresh` run gets us running again. I see that the base url for the references has been changed.
