### ISSUE TITLE
Add FHIR_Connectathon_17 results

### ISSUE THREAD

**Issue by bvdh** [DBCG/cqf-ruler#33]
Add the results of the 17th connectathon.

**Comment by c-schuler** [comment]
Apologies for the delay on committing this logic. I have committed a cleaned up and updated version of the resulting work done during the connectathon. There are some departures from the spec, which include returning the ndjson directly in the response body instead of downloadable files. I will be working on that as well as the DELETE request in future commits.

**Comment by bvdh** [comment]
I've merged my code with yours in the bulkdata branch.

**Comment by c-schuler** [comment]
Closing this...
